# Generated by Django 6.0.6 on 2026-10-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.CharField(blank=True, default='Image Not Uploaded', max_length=200),
        ),
    ]
