# Generated by Django 4.2.5 on 2023-10-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_amount_to_use_coupon',
            field=models.PositiveBigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
